In [1]:
import numpy as np 
import matplotlib.pyplot as plt

In [2]:
a = [[11, 12, 13], [21, 22, 23], [31, 32, 33]]
a

[[11, 12, 13], [21, 22, 23], [31, 32, 33]]

In [3]:
A = np.array(a)
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [4]:
A.ndim

2

In [5]:
A.size

9

In [6]:
A.shape

(3, 3)

In [7]:
A[1, 2]

23

In [8]:
A[1][2]

23

In [9]:
A[0][0]

11

In [11]:
A[0][0 : 2]

array([11, 12])

In [13]:
A[0:2, 2]

array([13, 23])

In [14]:
X = np.array([[1, 0], [0, 1]])
X

array([[1, 0],
       [0, 1]])

In [15]:
Y = np.array([[2, 1], [1, 2]])
Y

array([[2, 1],
       [1, 2]])

In [17]:
Z = X + Y
Z

array([[3, 1],
       [1, 3]])

In [18]:
Y = np.array([[2, 1], [1, 2]]) 
Y

array([[2, 1],
       [1, 2]])

In [19]:
Z = 2 * Y
Z

array([[4, 2],
       [2, 4]])

In [20]:
Y = np.array([[2, 1], [1, 2]]) 
Y

array([[2, 1],
       [1, 2]])

In [21]:
X = np.array([[1, 0], [0, 1]]) 
X

array([[1, 0],
       [0, 1]])

In [22]:
Z = X * Y
Z

array([[2, 0],
       [0, 2]])

In [23]:
A = np.array([[0, 1, 1], [1, 0, 1]])
A

array([[0, 1, 1],
       [1, 0, 1]])

In [24]:
B = np.array([[1, 1], [1, 1], [-1, 1]])
B

array([[ 1,  1],
       [ 1,  1],
       [-1,  1]])

In [26]:
Z = np.dot(A,B)
Z

array([[0, 2],
       [0, 2]])

In [27]:
np.sin(Z)

array([[0.        , 0.90929743],
       [0.        , 0.90929743]])

In [28]:
C = np.array([[1,1],[2,2],[3,3]])
C

array([[1, 1],
       [2, 2],
       [3, 3]])

In [29]:
C.T

array([[1, 2, 3],
       [1, 2, 3]])

In [30]:
a = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
a

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [36]:
A = np.array(a)
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [37]:
np.size(a)

12

In [38]:
A.size

12

In [41]:
A[0][0:2]

array([1, 2])

In [42]:
B = np.array([[0, 1], [1, 0], [1, 1], [-1, 0]])
B

array([[ 0,  1],
       [ 1,  0],
       [ 1,  1],
       [-1,  0]])

In [45]:
X = np.dot(A,B)
X

array([[ 1,  4],
       [ 5, 12],
       [ 9, 20]])